/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Message {
  'id' : bigint,
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'productId' : bigint,
  'timestamp' : Time,
}
export interface ProductWithShopDetails {
  'id' : bigint,
  'name' : string,
  'shop' : ShopProfile,
  'description' : string,
  'price' : bigint,
}
export interface ShopProfile {
  'id' : bigint,
  'locationUrl' : string,
  'owner' : Principal,
  'name' : string,
  'distanceKm' : number,
  'address' : string,
  'rating' : bigint,
  'priceInfo' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseProductsWithShop' : ActorMethod<[], Array<ProductWithShopDetails>>,
  'createProduct' : ActorMethod<[bigint, string, string, bigint], bigint>,
  'createShopProfile' : ActorMethod<
    [string, bigint, string, number, string, string, string],
    bigint
  >,
  'getAllShops' : ActorMethod<[], Array<ShopProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartItems' : ActorMethod<[], Array<CartItem>>,
  'getChatMessages' : ActorMethod<[bigint], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendBargainRequest' : ActorMethod<[bigint, bigint, [] | [string]], bigint>,
  'sendMessage' : ActorMethod<[Principal, string, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];