/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductAgeTime = IDL.Variant({
  'days' : IDL.Nat,
  'months' : IDL.Nat,
  'brandNew' : IDL.Null,
  'unknown' : IDL.Null,
  'years' : IDL.Nat,
});
export const ProductAge = IDL.Record({
  'time' : ProductAgeTime,
  'conditionDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShopProfile = IDL.Record({
  'id' : IDL.Nat,
  'locationUrl' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'priceInfo' : IDL.Text,
  'phone' : IDL.Text,
});
export const VerificationLabel = IDL.Record({
  'labelText' : IDL.Text,
  'description' : IDL.Text,
});
export const Condition = IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null });
export const ProductWithShopDetails = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Opt(ProductAge),
  'photoBlobs' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'returnPolicy' : IDL.Text,
  'name' : IDL.Text,
  'shop' : ShopProfile,
  'description' : IDL.Text,
  'productVerificationLabels' : IDL.Vec(VerificationLabel),
  'price' : IDL.Nat,
  'listingQualityScore' : IDL.Opt(IDL.Nat),
  'condition' : Condition,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BargainRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'customer' : IDL.Principal,
  'shopkeeper' : IDL.Principal,
  'note' : IDL.Opt(IDL.Text),
  'productId' : IDL.Nat,
  'desiredPrice' : IDL.Nat,
  'timestamp' : Time,
  'mutuallyAccepted' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Insurance = IDL.Record({
  'premium' : IDL.Nat,
  'name' : IDL.Text,
  'details' : IDL.Text,
  'coverageAmount' : IDL.Nat,
});
export const CartTotal = IDL.Record({
  'total' : IDL.Nat,
  'insurance' : IDL.Opt(Insurance),
  'cartItems' : IDL.Vec(CartItem),
  'insurancePremium' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'productId' : IDL.Nat,
  'timestamp' : Time,
});
export const DeliveryStatus = IDL.Variant({
  'driver_pending_assignment' : IDL.Null,
  'pending' : IDL.Null,
  'in_transit' : IDL.Null,
  'completed' : IDL.Null,
  'driver_assigned' : IDL.Null,
  'delivered' : IDL.Null,
  'picking_up' : IDL.Null,
  'failed' : IDL.Null,
});
export const DeliveryOption = IDL.Variant({
  'pickup' : IDL.Null,
  'delivery' : IDL.Null,
});
export const DeliveryOrder = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeliveryStatus,
  'driverId' : IDL.Opt(IDL.Nat),
  'completionCode' : IDL.Text,
  'shopId' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'dropoffLocation' : IDL.Text,
  'customer' : IDL.Principal,
  'deliveryOption' : DeliveryOption,
  'timestamp' : Time,
  'pickupLocation' : IDL.Text,
});
export const ShopkeeperAction = IDL.Variant({
  'liked' : IDL.Null,
  'in_cart' : IDL.Null,
});
export const ShopkeeperNotification = IDL.Record({
  'action' : ShopkeeperAction,
  'user' : IDL.Principal,
  'productId' : IDL.Nat,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Opt(ProductAge),
  'photoBlobs' : IDL.Opt(IDL.Vec(ExternalBlob)),
  'shopId' : IDL.Nat,
  'returnPolicy' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productVerificationLabels' : IDL.Vec(VerificationLabel),
  'price' : IDL.Nat,
  'listingQualityScore' : IDL.Opt(IDL.Nat),
  'condition' : Condition,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBargain' : IDL.Func([IDL.Nat], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'adminBrowseProductsWithShop' : IDL.Func(
      [],
      [IDL.Vec(ProductWithShopDetails)],
      ['query'],
    ),
  'adminDeleteProduct' : IDL.Func([IDL.Nat], [], []),
  'adminUpdateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Vec(ExternalBlob)),
        Condition,
        IDL.Text,
        IDL.Opt(ProductAge),
        IDL.Vec(VerificationLabel),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bargainsByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BargainRequest)],
      ['query'],
    ),
  'browseProductsWithShop' : IDL.Func(
      [],
      [IDL.Vec(ProductWithShopDetails)],
      ['query'],
    ),
  'calculateDeliveryFee' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [IDL.Nat],
      ['query'],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Vec(ExternalBlob)),
        Condition,
        IDL.Text,
        IDL.Opt(ProductAge),
        IDL.Vec(VerificationLabel),
      ],
      [IDL.Nat],
      [],
    ),
  'createShopProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllShops' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCartTotalWithInsurance' : IDL.Func([], [CartTotal], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getDefaultInsuranceOptions' : IDL.Func([], [IDL.Vec(Insurance)], ['query']),
  'getOwnDeliveryOrders' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
  'getOwnShopProfiles' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
  'getProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProductWithShopDetails)],
      ['query'],
    ),
  'getProductsForShop' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductWithShopDetails)],
      ['query'],
    ),
  'getSelectedInsurance' : IDL.Func([], [IDL.Opt(Insurance)], ['query']),
  'getShopkeeperNotifications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ShopkeeperNotification)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'hasLikedProduct' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProduct' : IDL.Func([IDL.Nat], [], []),
  'recommendBestInsurance' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Insurance)],
      ['query'],
    ),
  'registerDeliveryPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'removeLike' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectInsurance' : IDL.Func([IDL.Opt(Insurance)], [], []),
  'sendBargainRequest' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'setDeliveryPartnerAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Vec(ExternalBlob)),
        Condition,
        IDL.Text,
        IDL.Opt(ProductAge),
        IDL.Vec(VerificationLabel),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductAgeTime = IDL.Variant({
    'days' : IDL.Nat,
    'months' : IDL.Nat,
    'brandNew' : IDL.Null,
    'unknown' : IDL.Null,
    'years' : IDL.Nat,
  });
  const ProductAge = IDL.Record({
    'time' : ProductAgeTime,
    'conditionDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShopProfile = IDL.Record({
    'id' : IDL.Nat,
    'locationUrl' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'priceInfo' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VerificationLabel = IDL.Record({
    'labelText' : IDL.Text,
    'description' : IDL.Text,
  });
  const Condition = IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null });
  const ProductWithShopDetails = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Opt(ProductAge),
    'photoBlobs' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'returnPolicy' : IDL.Text,
    'name' : IDL.Text,
    'shop' : ShopProfile,
    'description' : IDL.Text,
    'productVerificationLabels' : IDL.Vec(VerificationLabel),
    'price' : IDL.Nat,
    'listingQualityScore' : IDL.Opt(IDL.Nat),
    'condition' : Condition,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BargainRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'customer' : IDL.Principal,
    'shopkeeper' : IDL.Principal,
    'note' : IDL.Opt(IDL.Text),
    'productId' : IDL.Nat,
    'desiredPrice' : IDL.Nat,
    'timestamp' : Time,
    'mutuallyAccepted' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Insurance = IDL.Record({
    'premium' : IDL.Nat,
    'name' : IDL.Text,
    'details' : IDL.Text,
    'coverageAmount' : IDL.Nat,
  });
  const CartTotal = IDL.Record({
    'total' : IDL.Nat,
    'insurance' : IDL.Opt(Insurance),
    'cartItems' : IDL.Vec(CartItem),
    'insurancePremium' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'productId' : IDL.Nat,
    'timestamp' : Time,
  });
  const DeliveryStatus = IDL.Variant({
    'driver_pending_assignment' : IDL.Null,
    'pending' : IDL.Null,
    'in_transit' : IDL.Null,
    'completed' : IDL.Null,
    'driver_assigned' : IDL.Null,
    'delivered' : IDL.Null,
    'picking_up' : IDL.Null,
    'failed' : IDL.Null,
  });
  const DeliveryOption = IDL.Variant({
    'pickup' : IDL.Null,
    'delivery' : IDL.Null,
  });
  const DeliveryOrder = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeliveryStatus,
    'driverId' : IDL.Opt(IDL.Nat),
    'completionCode' : IDL.Text,
    'shopId' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'dropoffLocation' : IDL.Text,
    'customer' : IDL.Principal,
    'deliveryOption' : DeliveryOption,
    'timestamp' : Time,
    'pickupLocation' : IDL.Text,
  });
  const ShopkeeperAction = IDL.Variant({
    'liked' : IDL.Null,
    'in_cart' : IDL.Null,
  });
  const ShopkeeperNotification = IDL.Record({
    'action' : ShopkeeperAction,
    'user' : IDL.Principal,
    'productId' : IDL.Nat,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Opt(ProductAge),
    'photoBlobs' : IDL.Opt(IDL.Vec(ExternalBlob)),
    'shopId' : IDL.Nat,
    'returnPolicy' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productVerificationLabels' : IDL.Vec(VerificationLabel),
    'price' : IDL.Nat,
    'listingQualityScore' : IDL.Opt(IDL.Nat),
    'condition' : Condition,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBargain' : IDL.Func([IDL.Nat], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'adminBrowseProductsWithShop' : IDL.Func(
        [],
        [IDL.Vec(ProductWithShopDetails)],
        ['query'],
      ),
    'adminDeleteProduct' : IDL.Func([IDL.Nat], [], []),
    'adminUpdateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Vec(ExternalBlob)),
          Condition,
          IDL.Text,
          IDL.Opt(ProductAge),
          IDL.Vec(VerificationLabel),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bargainsByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BargainRequest)],
        ['query'],
      ),
    'browseProductsWithShop' : IDL.Func(
        [],
        [IDL.Vec(ProductWithShopDetails)],
        ['query'],
      ),
    'calculateDeliveryFee' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [IDL.Nat],
        ['query'],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Vec(ExternalBlob)),
          Condition,
          IDL.Text,
          IDL.Opt(ProductAge),
          IDL.Vec(VerificationLabel),
        ],
        [IDL.Nat],
        [],
      ),
    'createShopProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllShops' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCartTotalWithInsurance' : IDL.Func([], [CartTotal], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getDefaultInsuranceOptions' : IDL.Func(
        [],
        [IDL.Vec(Insurance)],
        ['query'],
      ),
    'getOwnDeliveryOrders' : IDL.Func([], [IDL.Vec(DeliveryOrder)], ['query']),
    'getOwnShopProfiles' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
    'getProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProductWithShopDetails)],
        ['query'],
      ),
    'getProductsForShop' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductWithShopDetails)],
        ['query'],
      ),
    'getSelectedInsurance' : IDL.Func([], [IDL.Opt(Insurance)], ['query']),
    'getShopkeeperNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ShopkeeperNotification)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'hasLikedProduct' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProduct' : IDL.Func([IDL.Nat], [], []),
    'recommendBestInsurance' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Insurance)],
        ['query'],
      ),
    'registerDeliveryPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'removeLike' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectInsurance' : IDL.Func([IDL.Opt(Insurance)], [], []),
    'sendBargainRequest' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'setDeliveryPartnerAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Vec(ExternalBlob)),
          Condition,
          IDL.Text,
          IDL.Opt(ProductAge),
          IDL.Vec(VerificationLabel),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };