/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShopProfile = IDL.Record({
  'id' : IDL.Nat,
  'locationUrl' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'priceInfo' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductWithShopDetails = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'shop' : ShopProfile,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'productId' : IDL.Nat,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseProductsWithShop' : IDL.Func(
      [],
      [IDL.Vec(ProductWithShopDetails)],
      ['query'],
    ),
  'createProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createShopProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllShops' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendBargainRequest' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShopProfile = IDL.Record({
    'id' : IDL.Nat,
    'locationUrl' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'priceInfo' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductWithShopDetails = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'shop' : ShopProfile,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'productId' : IDL.Nat,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseProductsWithShop' : IDL.Func(
        [],
        [IDL.Vec(ProductWithShopDetails)],
        ['query'],
      ),
    'createProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createShopProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllShops' : IDL.Func([], [IDL.Vec(ShopProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartItems' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getChatMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendBargainRequest' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };